### ISSUE TITLE
Container image for AlmaLinux 10 Beta?

### ISSUE THREAD

**Issue by der-eismann** [AlmaLinux/container-images#30]
Hey, sorry for being so impatient, but since the [AlmaLinux 10 Beta was announced a week ago](https://almalinux.org/blog/2024-12-10-almalinux-10-0-beta-now-available/) I am waiting for a container image to play with. Will it come anytime soon or is any additional work required?
Thanks!

**Comment by yuravk** [comment]
Hello,

You may pull the following images:
```
quay.io/almalinuxautobot/almalinux:10
quay.io/almalinuxautobot/10-base:latest
quay.io/almalinuxautobot/10-micro:latest
quay.io/almalinuxautobot/10-minimal:latest
quay.io/almalinuxautobot/10-init:latest
```

**Comment by der-eismann** [comment]
Ah, I was only looking on Docker Hub and not on Quay. Thanks!
